spring.application.name=license-manager
spring.datasource.url=jdbc:mysql://localhost:3306/license_manager
spring.datasource.username=root
spring.datasource.password=khanna2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
