spring.application.name=kanban-board
spring.datasource.url=jdbc:mysql://localhost:3306/kanban_db
spring.datasource.username=root
spring.datasource.password=khanna2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true